#!/usr/bin/python
# -*- coding: utf-8; mode: python; tab-width: 3; indent-tabs-mode: nil -*-
#
# Copyright 2012, 2013
# Raffaello D. Di Napoli
#
# This file is part of kernel-tools.
#
# kernel-tools is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# kernel-tools is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with kernel-tools. If not,
# see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------------

"""Lists external firmware and/or modules for Linux along with the packages that installed them."""



####################################################################################################
# __main__

if __name__ == '__main__':
   import os
   import sys
   # Get the full path of this script.
   sDir = os.path.dirname(os.path.abspath(sys.argv[0]))
   # Setup the PATH environment variable to load kerneltools.
   sys.path.append(sDir)
   import kerneltools

   bFiles = False
   bFirmware = False
   bModules = False
   bPackages = False

   # Scan the command line.
   for sArg in sys.argv[1:]:
      if sArg == '-f' or sArg == '--files':
         bFiles = True
      elif sArg == '-m' or sArg == '--modules':
         bModules = True
      elif sArg == '-p' or sArg == '--packages':
         bPackages = True
      elif sArg == '-w' or sArg == '--firmware':
         bFirmware = True
      else:
         import textwrap
         sys.stdout.write(textwrap.dedent("""\
            Usage: kernel-lsext [options]

            Options:
            -f, --files     Show matching files; default.
            -w, --firmware  List external firmware installed by non-kernel packages.
                --help      Show this informative message.
            -m, --modules   List modules installed by non-kernel packages.
            -p, --packages  Change -m and/or -w to only show the containing packages,
                            overriding -f if not specified. If combined with -f, show
                            packages on the same line as the files they contain.
         """))
         if sArg == '--help':
            sys.exit(0)
         else:
            sys.exit(1)

   eme = kerneltools.ExternalModuleEnumerator(bFirmware = bFirmware, bModules = bModules)
   if bPackages:
      if bFiles:
         for sPackage, listFiles in eme.packages_and_files():
            # Output the package and its files.
            sys.stdout.write(sPackage + ' ' + ' '.join(listFiles) + '\n')
      else:
         for sPackage, listFiles in eme.packages_and_files():
            # Output packages only.
            sys.stdout.write(sPackage + '\n')
   else:
      for sFilePath in eme.files():
         # Output files only, one per line.
         sys.stdout.write(sFilePath + '\n')

   sys.exit(0)

